//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/Input/Input Objects/LauncherInputActionMappings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @LauncherInputActionMappings : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @LauncherInputActionMappings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""LauncherInputActionMappings"",
    ""maps"": [
        {
            ""name"": ""Launcher"",
            ""id"": ""c5d3eede-322e-4470-9263-5b0a29bdb5b9"",
            ""actions"": [
                {
                    ""name"": ""ToogleView"",
                    ""type"": ""Button"",
                    ""id"": ""f08dcef6-a59e-45d7-8c10-9aa0e7787e09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnterUAEWaters"",
                    ""type"": ""Button"",
                    ""id"": ""ac41a82b-3609-4470-b7ed-11064a9ba487"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3078a785-575f-45a9-9d7c-9ed63571e990"",
                    ""path"": ""<Keyboard>/#(X)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToogleView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fcbf3f1-e4e3-4119-b76b-1cc662e82037"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToogleView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d641e782-edf9-40c1-8d47-4470241c3454"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterUAEWaters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f09a58f1-753d-4c7a-abd8-79373aeb2289"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterUAEWaters"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Launcher
        m_Launcher = asset.FindActionMap("Launcher", throwIfNotFound: true);
        m_Launcher_ToogleView = m_Launcher.FindAction("ToogleView", throwIfNotFound: true);
        m_Launcher_EnterUAEWaters = m_Launcher.FindAction("EnterUAEWaters", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Launcher
    private readonly InputActionMap m_Launcher;
    private ILauncherActions m_LauncherActionsCallbackInterface;
    private readonly InputAction m_Launcher_ToogleView;
    private readonly InputAction m_Launcher_EnterUAEWaters;
    public struct LauncherActions
    {
        private @LauncherInputActionMappings m_Wrapper;
        public LauncherActions(@LauncherInputActionMappings wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToogleView => m_Wrapper.m_Launcher_ToogleView;
        public InputAction @EnterUAEWaters => m_Wrapper.m_Launcher_EnterUAEWaters;
        public InputActionMap Get() { return m_Wrapper.m_Launcher; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LauncherActions set) { return set.Get(); }
        public void SetCallbacks(ILauncherActions instance)
        {
            if (m_Wrapper.m_LauncherActionsCallbackInterface != null)
            {
                @ToogleView.started -= m_Wrapper.m_LauncherActionsCallbackInterface.OnToogleView;
                @ToogleView.performed -= m_Wrapper.m_LauncherActionsCallbackInterface.OnToogleView;
                @ToogleView.canceled -= m_Wrapper.m_LauncherActionsCallbackInterface.OnToogleView;
                @EnterUAEWaters.started -= m_Wrapper.m_LauncherActionsCallbackInterface.OnEnterUAEWaters;
                @EnterUAEWaters.performed -= m_Wrapper.m_LauncherActionsCallbackInterface.OnEnterUAEWaters;
                @EnterUAEWaters.canceled -= m_Wrapper.m_LauncherActionsCallbackInterface.OnEnterUAEWaters;
            }
            m_Wrapper.m_LauncherActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToogleView.started += instance.OnToogleView;
                @ToogleView.performed += instance.OnToogleView;
                @ToogleView.canceled += instance.OnToogleView;
                @EnterUAEWaters.started += instance.OnEnterUAEWaters;
                @EnterUAEWaters.performed += instance.OnEnterUAEWaters;
                @EnterUAEWaters.canceled += instance.OnEnterUAEWaters;
            }
        }
    }
    public LauncherActions @Launcher => new LauncherActions(this);
    public interface ILauncherActions
    {
        void OnToogleView(InputAction.CallbackContext context);
        void OnEnterUAEWaters(InputAction.CallbackContext context);
    }
}
