//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Scripts/Input/Input Objects/OperatorInputActionMappings.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @OperatorInputActionMappings : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @OperatorInputActionMappings()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""OperatorInputActionMappings"",
    ""maps"": [
        {
            ""name"": ""Operator"",
            ""id"": ""c5d3eede-322e-4470-9263-5b0a29bdb5b9"",
            ""actions"": [
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""daddc2f8-c22a-4731-8494-7bf200f80f43"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LinearMovement"",
                    ""type"": ""Value"",
                    ""id"": ""0c7d97f8-00f3-4ede-b2b8-e6599a69ea5d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToogleVRScreen"",
                    ""type"": ""Button"",
                    ""id"": ""ac41a82b-3609-4470-b7ed-11064a9ba487"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleView"",
                    ""type"": ""Button"",
                    ""id"": ""c9aa0b20-199f-4e54-8623-50903afc51c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectParkingArea"",
                    ""type"": ""Button"",
                    ""id"": ""8cc54b31-b5db-49b9-aeae-9076fa303019"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LeftRight"",
                    ""id"": ""969473e5-640d-403c-934d-d0d75600c9f5"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""0dd70163-6676-41e5-9063-63cf4b3263e8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""c572311f-665e-4acb-a755-2df2bc73e25e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""0e5e678f-0b15-4f7e-aeb6-60a13f0f2d28"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ec44c317-ed76-4337-994b-610c96ad702b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4724fdaa-86db-4293-ba10-65f95e78534d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""df38edca-8dfd-4885-bd5e-d4f0a252a760"",
                    ""path"": ""<XRController>{RightHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""UpDown"",
                    ""id"": ""1888fe77-48f5-4ea8-bd34-551e1e79ce56"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""60a42ae7-025a-4fd6-8608-eb4258044859"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""de84322c-d94e-42d1-a8f4-9cd8bf63b5cf"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""cc5f4bb1-93c2-4d72-95a3-893a074ddd28"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2476c3ab-a9ee-4c89-be0f-87292ec82093"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d8a1dafa-e5dd-43e9-8318-17536003b020"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e6500a2-b236-455d-bd4c-d7b936a4e9cf"",
                    ""path"": ""<XRController>{LeftHand}/primary2DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d641e782-edf9-40c1-8d47-4470241c3454"",
                    ""path"": ""<Keyboard>/#(B)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToogleVRScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f09a58f1-753d-4c7a-abd8-79373aeb2289"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToogleVRScreen"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb3091c4-8264-4ed9-a8fc-b29d037fe5e5"",
                    ""path"": ""<Keyboard>/#(X)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3199175-6e01-46ae-83cc-609db54f83fe"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26a5e2e7-0939-458e-abd9-dd65caa308aa"",
                    ""path"": ""<Keyboard>/#(Y)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectParkingArea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ee80383-8d7f-464c-9088-1b4327077265"",
                    ""path"": ""<OculusTouchController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectParkingArea"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Operator
        m_Operator = asset.FindActionMap("Operator", throwIfNotFound: true);
        m_Operator_Steer = m_Operator.FindAction("Steer", throwIfNotFound: true);
        m_Operator_LinearMovement = m_Operator.FindAction("LinearMovement", throwIfNotFound: true);
        m_Operator_ToogleVRScreen = m_Operator.FindAction("ToogleVRScreen", throwIfNotFound: true);
        m_Operator_ToggleView = m_Operator.FindAction("ToggleView", throwIfNotFound: true);
        m_Operator_SelectParkingArea = m_Operator.FindAction("SelectParkingArea", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Operator
    private readonly InputActionMap m_Operator;
    private IOperatorActions m_OperatorActionsCallbackInterface;
    private readonly InputAction m_Operator_Steer;
    private readonly InputAction m_Operator_LinearMovement;
    private readonly InputAction m_Operator_ToogleVRScreen;
    private readonly InputAction m_Operator_ToggleView;
    private readonly InputAction m_Operator_SelectParkingArea;
    public struct OperatorActions
    {
        private @OperatorInputActionMappings m_Wrapper;
        public OperatorActions(@OperatorInputActionMappings wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steer => m_Wrapper.m_Operator_Steer;
        public InputAction @LinearMovement => m_Wrapper.m_Operator_LinearMovement;
        public InputAction @ToogleVRScreen => m_Wrapper.m_Operator_ToogleVRScreen;
        public InputAction @ToggleView => m_Wrapper.m_Operator_ToggleView;
        public InputAction @SelectParkingArea => m_Wrapper.m_Operator_SelectParkingArea;
        public InputActionMap Get() { return m_Wrapper.m_Operator; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OperatorActions set) { return set.Get(); }
        public void SetCallbacks(IOperatorActions instance)
        {
            if (m_Wrapper.m_OperatorActionsCallbackInterface != null)
            {
                @Steer.started -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSteer;
                @Steer.performed -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSteer;
                @Steer.canceled -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSteer;
                @LinearMovement.started -= m_Wrapper.m_OperatorActionsCallbackInterface.OnLinearMovement;
                @LinearMovement.performed -= m_Wrapper.m_OperatorActionsCallbackInterface.OnLinearMovement;
                @LinearMovement.canceled -= m_Wrapper.m_OperatorActionsCallbackInterface.OnLinearMovement;
                @ToogleVRScreen.started -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToogleVRScreen;
                @ToogleVRScreen.performed -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToogleVRScreen;
                @ToogleVRScreen.canceled -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToogleVRScreen;
                @ToggleView.started -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToggleView;
                @ToggleView.performed -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToggleView;
                @ToggleView.canceled -= m_Wrapper.m_OperatorActionsCallbackInterface.OnToggleView;
                @SelectParkingArea.started -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSelectParkingArea;
                @SelectParkingArea.performed -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSelectParkingArea;
                @SelectParkingArea.canceled -= m_Wrapper.m_OperatorActionsCallbackInterface.OnSelectParkingArea;
            }
            m_Wrapper.m_OperatorActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @LinearMovement.started += instance.OnLinearMovement;
                @LinearMovement.performed += instance.OnLinearMovement;
                @LinearMovement.canceled += instance.OnLinearMovement;
                @ToogleVRScreen.started += instance.OnToogleVRScreen;
                @ToogleVRScreen.performed += instance.OnToogleVRScreen;
                @ToogleVRScreen.canceled += instance.OnToogleVRScreen;
                @ToggleView.started += instance.OnToggleView;
                @ToggleView.performed += instance.OnToggleView;
                @ToggleView.canceled += instance.OnToggleView;
                @SelectParkingArea.started += instance.OnSelectParkingArea;
                @SelectParkingArea.performed += instance.OnSelectParkingArea;
                @SelectParkingArea.canceled += instance.OnSelectParkingArea;
            }
        }
    }
    public OperatorActions @Operator => new OperatorActions(this);
    public interface IOperatorActions
    {
        void OnSteer(InputAction.CallbackContext context);
        void OnLinearMovement(InputAction.CallbackContext context);
        void OnToogleVRScreen(InputAction.CallbackContext context);
        void OnToggleView(InputAction.CallbackContext context);
        void OnSelectParkingArea(InputAction.CallbackContext context);
    }
}
